"use client"
import Head from 'next/head';
import { FC, useState } from 'react';

type WorkExperience = {
    id: number;
    title: string;
    company: string;
    duration: string;
    description: string;
    imageUrl: string;
}

const WorkExperience: FC = () => {


    const [workExperience, setWorkExperience] = useState<WorkExperience[]>([
        {
            id: 0,
            title: 'Sales/Marketing Specialist & Founder',
            company: 'OnSocial Agency',
            duration: 'Jan 2017 - Present · 7 yrs 5 mos',
            description: 'We help businesses worldwide to grow their social presence within Instagram and Facebook.',
            imageUrl: "/image/svg/work.svg",
        },
        {
            id: 1,
            title: 'Independent Consultant',
            company: 'Business Consultancy - Freelance',
            duration: 'Aug 2014 - Feb 2022 · 7 yrs 6 mos',
            description: 'I\'m providing consultations for companies going to start operating within Ukraine.',
            imageUrl: '/image/svg/work.svg',
        },
        {
            id: 2,
            title: 'Operations Manager & Founder',
            company: 'Online Language School - Part-time',
            duration: 'Dec 2015 - May 2018 · 2 yrs 6 mos',
            description: 'We offer online Ukrainian language courses with individual tutors. Students enjoy the best Ukrainian native-speaking teachers.',
            imageUrl: '/image/svg/work.svg',
        },
        {
            id: 3,
            title: 'Operations Manager & Founder',
            company: 'Online Language School - Part-time',
            duration: 'Dec 2015 - May 2018 · 2 yrs 6 mos',
            description: 'We offer online Ukrainian language courses with individual tutors. Students enjoy the best Ukrainian native-speaking teachers.',
            imageUrl: '/image/svg/work.svg',
        },
        {
            id: 4,
            title: 'Operations Manager & Founder',
            company: 'Online Language School - Part-time',
            duration: 'Dec 2015 - May 2018 · 2 yrs 6 mos',
            description: 'We offer online Ukrainian language courses with individual tutors. Students enjoy the best Ukrainian native-speaking teachers.',
            imageUrl: '/image/svg/work.svg',
        },
        {
            id: 5,
            title: 'Operations Manager & Founder',
            company: 'Online Language School - Part-time',
            duration: 'Dec 2015 - May 2018 · 2 yrs 6 mos',
            description: 'We offer online Ukrainian language courses with individual tutors. Students enjoy the best Ukrainian native-speaking teachers.',
            imageUrl: '/image/svg/work.svg',
        },
        {
            id: 6,
            title: 'Operations Manager & Founder',
            company: 'Online Language School - Part-time',
            duration: 'Dec 2015 - May 2018 · 2 yrs 6 mos',
            description: 'We offer online Ukrainian language courses with individual tutors. Students enjoy the best Ukrainian native-speaking teachers.',
            imageUrl: '/image/svg/work.svg',
        },
    ])

    const [seeAll, setSeeAll] = useState<boolean>(false);
    const [length, setLength] = useState<number>(workExperience.length - 3);

    const displayedExperiences = workExperience.slice(0, 3);

    return (
        <div className='bg-white'>
            <Head>
                <title>Work Experience</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="py-10">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <h1 className="text-2xl font-bold mb-8">Work experience</h1>
                    <div>
                        {
                            seeAll ? (
                                workExperience.map((experience, index) => (
                                    <div className="flex items-start space-x-4 py-4" key={experience.id}>
                                        <img src={experience.imageUrl} alt={experience.title} className="w-5 h-5" />
                                        <div>
                                            <h3 className="text-lg font-semibold">{experience.title}</h3>
                                            <p className="text-gray-600">{experience.company}</p>
                                            <p className="text-gray-600">{experience.duration}</p>
                                            <p className="mt-2">{experience.description}</p>
                                        </div>
                                    </div>
                                ))
                            ) : (
                                displayedExperiences.map((experience, index) => (
                                    <div className="flex items-start space-x-4 py-4" key={experience.id}>
                                        <img src={experience.imageUrl} alt={experience.title} className="w-5 h-5" />
                                        <div>
                                            <h3 className="text-lg font-semibold">{experience.title}</h3>
                                            <p className="text-gray-600">{experience.company}</p>
                                            <p className="text-gray-600">{experience.duration}</p>
                                            <p className="mt-2">{experience.description}</p>
                                        </div>
                                    </div>
                                ))
                            )
                        }
                    </div>
                    <div className="mt-6" onClick={() => setSeeAll(!seeAll)}>
                        <a className="text-blue-500 hover:underline cursor-pointer">{seeAll ? "See less" : "See all work experience" + "(" + length + ")"}</a>
                    </div>
                </div>
            </main>
        </div>
    );
}

export default WorkExperience;