import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ServicesProvider } from "./services/serviceContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Influencity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ServicesProvider>
          <main>{children}</main>
        </ServicesProvider>
      </body>
    </html>
  );
}
